//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datatbl_User
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_password { get; set; }
        public string user_full_name { get; set; }
        public string user_email { get; set; }
        public Nullable<bool> user_is_admin { get; set; }
        public string user_adress { get; set; }
        public string user_contact_no { get; set; }
        public Nullable<bool> user_is_active { get; set; }
    }
}
