//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datatbl_Book_Details
    {
        public int book_id { get; set; }
        public string book_title_name { get; set; }
        public string book_author_name { get; set; }
        public int book_genre_id { get; set; }
        public bool book_availability_status { get; set; }
    
        public virtual Permnt_tbl_Genre Permnt_tbl_Genre { get; set; }
    }
}
