//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryDBEntitiesModels : DbContext
    {
        public LibraryDBEntitiesModels()
            : base("name=LibraryDBEntitiesModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Permnt_tbl_Genre> Permnt_tbl_Genre { get; set; }
        public virtual DbSet<Datatbl_User> Datatbl_User { get; set; }
        public virtual DbSet<Datatbl_Book_Details> Datatbl_Book_Details { get; set; }
    }
}
