//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permnt_tbl_Genre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permnt_tbl_Genre()
        {
            this.Datatbl_Book_Details = new HashSet<Datatbl_Book_Details>();
        }
    
        public int permnt_tbl_genre_id { get; set; }
        public string permnt_tbl_genre_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Datatbl_Book_Details> Datatbl_Book_Details { get; set; }
    }
}
